### ISSUE TITLE
This game sucks

### ISSUE THREAD

**Issue by Brendan-Laking** [Ralph-scott/Rpg-Game#2]
### **This game sucks!** 
This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! This game sucks! 

- This game sucks! 
- This game sucks! 
- This game sucks! 
- This game sucks!

**Comment by Ralph-scott** [comment]
no
